# Site settings
title: R.E. Sprouse // Whispres
# baseurl: "N/A
# url: "localhost:4000" or "whispres.github.io"
repository: whispres.github.io
description: Personal and professional website for R.E. Sprouse // Whispres
local: en_US

# User settings
username: R.E. Sprouse
usertitle: Technical Writer
email: sprouse.re@gmail.com
twitter: Whisp_res
github:  Whispres
linkedin:  sprouse-re

#Gems/Plugins
plugins:
  - github-pages
  - jekyll-seo-tag
  - jekyll-sitemap

# Google-analytics
google-analytics:
  id: "UA-122323788-1"

markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

exclude: ['package.json', 'node_modules']
