# Site settings
title: R.E. Sprouse // Whispres
description: My professional development and achievments.
# baseurl: "/whispres" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: R.E. Sprouse
user_description: Technical Communicator, Chemist, Analyst, GitHub Volunteer and Cat Enthusiast
user_title: Technical Writer
email: sprouse.re@gmail.com
twitter_username: Whisp_res
github_username:  Whispres
linkedin_username:  sprouse-re

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
repository: whispres.github.io
